# Generated by Django 3.1.6 on 2021-02-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admnistrateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdp', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('poste', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mdp', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('titre', models.CharField(choices=[('Doctorant', 'Doctorant'), ('Maître de conférences', 'Maitre De Conferences'), ('Professeur des universités', 'Prof Des Universites'), ('Tuteur', 'Tuteur')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
