# Generated by Django 3.1.6 on 2021-02-02 00:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('listes', '0002_departement_etudiant_filiere_ufr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('niveaux', django_mysql.models.ListCharField(models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], default='L1', max_length=10), max_length=22, size=2)),
                ('types', models.CharField(choices=[('CM', 'Cm'), ('TD', 'Td')], default='CM', max_length=100)),
                ('debut', models.IntegerField(verbose_name=2021)),
                ('fin', models.IntegerField(verbose_name=2022)),
            ],
        ),
        migrations.RemoveField(
            model_name='etudiant',
            name='choices',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='niveaux',
            field=django_mysql.models.ListCharField(models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3'), ('M1', 'M1'), ('M2', 'M2')], default='L1', max_length=10), default=None, max_length=22, size=2),
        ),
    ]
