use gestion ;
TRUNCATE TABLE `auth_user_groups` ;
TRUNCATE TABLE `listes_admnistrateur` ;
TRUNCATE TABLE `listes_cours_filieres` ;
TRUNCATE TABLE `listes_etudiant_cours` ;
TRUNCATE TABLE `listes_professeur_cours` ;
TRUNCATE TABLE `listes_etudiant_filieres` ;
TRUNCATE TABLE `listes_document` ;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE `listes_ufr` ;
TRUNCATE `listes_etudiant` ;
TRUNCATE `listes_professeur` ;
TRUNCATE `listes_departement` ;
TRUNCATE `listes_filiere` ;
TRUNCATE `listes_cours` ;
TRUNCATE `auth_user` ;
SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO auth_user (`password`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES ('pbkdf2_sha256$216000$PQHyuL4tVbf5$hoL/QyURowVnU2b2D/nkDl6hUWSYRV6jQrGVZdZwxHY=','1','Admin et Prof','Marta','Rukoz Castillo','admin1@parisnanterre.fr','1','1','2021-02-09');
INSERT INTO auth_user (`password`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES ('pbkdf2_sha256$216000$PQHyuL4tVbf5$hoL/QyURowVnU2b2D/nkDl6hUWSYRV6jQrGVZdZwxHY=','1','Admin 2','Marie Pierre','Gervais','admin2@parisnanterre.fr','1','1', '2021-02-09');
INSERT INTO auth_user (`password`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES ('pbkdf2_sha256$216000$PQHyuL4tVbf5$hoL/QyURowVnU2b2D/nkDl6hUWSYRV6jQrGVZdZwxHY=','1','Prof 1','Emilie','Lebarbier','prof1@parisnanterre.fr','1','1', '2021-02-09');
INSERT INTO auth_user (`password`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES ('pbkdf2_sha256$216000$PQHyuL4tVbf5$hoL/QyURowVnU2b2D/nkDl6hUWSYRV6jQrGVZdZwxHY=','1','Prof 2','Pascal','Poizat','prof2@parisnanterre.fr','1','1', '2021-02-09');
INSERT INTO auth_user (`password`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES ('pbkdf2_sha256$216000$PQHyuL4tVbf5$hoL/QyURowVnU2b2D/nkDl6hUWSYRV6jQrGVZdZwxHY=','1','Prof 3','Reda','Bendraou','prof3@parisnanterre.fr','1','1', '2021-02-09');
INSERT INTO auth_user (`password`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES ('pbkdf2_sha256$216000$PQHyuL4tVbf5$hoL/QyURowVnU2b2D/nkDl6hUWSYRV6jQrGVZdZwxHY=','1','Prof 4','Fabrice','Legon','prof4@parisnanterre.fr','1','1', '2021-02-09');
INSERT INTO auth_user (`password`, `is_superuser`, `username`, `first_name`, `last_name`, `email`, `is_staff`, `is_active`, `date_joined`) VALUES ('pbkdf2_sha256$216000$PQHyuL4tVbf5$hoL/QyURowVnU2b2D/nkDl6hUWSYRV6jQrGVZdZwxHY=','1','Prof 5','François','Delbot','prof5@parisnanterre.fr','1','1', '2021-02-09');
INSERT INTO listes_admnistrateur (`poste`, `user_id`) VALUES ('Référente du Master 2 MIAGE Classique/Mixte','1');
INSERT INTO listes_admnistrateur (`poste`, `user_id`) VALUES ('Référente du Master 2 MIAGE Apprentissage','2');
INSERT INTO listes_ufr (`nom`) VALUES ('Sciences Economiques, Gestion, Mathématiques, Informatique');
INSERT INTO listes_ufr (`nom`) VALUES ('Droit et Science Politique');
INSERT INTO listes_departement (`nom`, `ufr_id`) VALUES ('Mathématiques et informatique','1');
INSERT INTO listes_departement (`nom`, `ufr_id`) VALUES ('Gestion','1');
INSERT INTO listes_departement (`nom`, `ufr_id`) VALUES ('Droit et Science Politique','2');
INSERT INTO listes_filiere (`nom`, `departement_id`) VALUES ('Méthodes Informatiques Appliquées à la Gestion des Entreprise','1');
INSERT INTO listes_filiere (`nom`, `departement_id`) VALUES ('Gestion','2');
INSERT INTO listes_filiere (`nom`, `departement_id`) VALUES ('Droit','3');
INSERT INTO listes_filiere (`nom`, `departement_id`) VALUES ('Economie','1');
INSERT INTO listes_filiere (`nom`, `departement_id`) VALUES ('Mathématiques et Informatique Appliqués aux Sciences Humaines et Sociales','1');
INSERT INTO listes_filiere (`nom`, `departement_id`) VALUES ('Droit du Numérique','3');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Macroéconomie : analyse conjoncturelle', 'L2', 'CM', '2020-09-04', '2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Tests et statistiques','L2','TD','2020-09-04','2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Probabilités','L2','TD','2020-09-04','2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Programmation Web et introduction PHP', 'L2', 'CM', '2020-09-04','2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Droit du commerce International','M1','CM','2020-09-04','2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Contentieux International et Européen','M1','TD','2020-09-04','2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Macroéconomie des pays émergents et en développement', 'L3', 'CM', '2020-09-04','2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Economie des comportements macroéconomiques','L3','CM','2020-09-04','2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Projet Systèmes d’Information et données','M2','TD','2020-09-04','2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Applications du Machine learning', 'M2', 'CM', '2020-09-04', '2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Construction des problèmes publics', 'M1', 'CM', '2020-09-04', '2021-06-01');
INSERT INTO listes_cours (`nom`, `niveaux`, `types`, `debut`, `fin`) VALUES ('Genre et politique', 'M1', 'CM', '2020-09-04', '2021-06-01');
INSERT INTO listes_professeur (`titre`, `user_id`) VALUES ('Autre','3');
INSERT INTO listes_professeur (`titre`, `user_id`) VALUES ('Professeur des universités','4');
INSERT INTO listes_professeur (`titre`, `user_id`) VALUES ('Professeur des universités','5');
INSERT INTO listes_professeur (`titre`, `user_id`) VALUES ('Maître de conférences', '6');
INSERT INTO listes_professeur (`titre`, `user_id`) VALUES ('Tuteur','7');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004486', 'Batumbo', 'Sophie', '36004486@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('39015814', 'Hormat', 'Ibtissame', '39015814@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('34006171', 'Vu', 'Phi Yen', '34006171@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36001791', 'Allin', 'Amélie','36001791@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('40003037', 'Ait Tilat', 'Sahar', ' 40003037@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('37009904', 'D’Auber de Peyrelongue', 'Aurélien','37009904@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('40013255', 'Ibrahim', 'Imad','40013255@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('40016176', 'Ikene', 'Katia', '40016176@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36001538', 'Anani Agondja', 'Thibault','36001538@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36001953', 'Lourme', 'Matthieu','36001953@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004587', 'Auron', 'Simon','36004587@parisnanterre.fr', 'L2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('37004889', 'Balon', 'Oumaïma','37004889@parisnanterre.fr', 'L2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36002345', 'Lahat', 'Imen', '36002345@parisnanterre.fr', 'L2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('39003456', 'Abédjan', 'Aubédine','39003456@parisnanterre.fr', 'L2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004588', 'Passet', 'Eléonore', '36004588@parisnanterre.fr', 'L2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('38009982', 'Ben Sala', 'Mehdi', '38009982@parisnanterre.fr', 'L2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36005483', 'Nouzbec', 'Antoine','36005483@parisnanterre.fr', 'L2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004587', 'Venua', 'Phillipe', '36004587@parisnanterre.fr', 'L1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004528', 'Flores', 'Gabriel','36004528@parisnanterre.fr', 'L1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006529', 'De Montbront', 'Jacques', '36006529@parisnanterre.fr', 'L1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004530', 'Daydera', 'Guillaume','36004530@parisnanterre.fr', 'L1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004531', 'Viger', 'Alice', '36004531@parisnanterre.fr', 'L1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004532', 'Costes', 'Juliette','36004532@parisnanterre.fr', 'L2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004533', 'Gavignon', 'Yaëlle', '36004533@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004534', 'Sylvain', 'Mathieu','36004534@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004535', 'Pentou', 'Chloé', '36004535@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36004536', 'Coussot', 'Aurélie','36004536@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006537', 'Fiedler', 'Lia', '36006537@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006538', 'Macina', 'Rahmatoulaye','36006538@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006539', 'Bouchard', 'Sarah', '36006539@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('35002072', 'Serres', 'Alexandre', '35002072@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006544', 'Argint', 'Dorina','36006544@parisnanterre.fr', 'M2');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006565', 'Plouf', 'Agathe', '36006565@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006566', 'Foubar', 'Lou', '36006566@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006567', 'Berger', 'Titouan', '36006567@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006568', 'Menta', 'Xavier', '36006568@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006569', 'Fimbu', 'Jason', '36006569@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006570', 'Loketo', 'Keysha', '36006570@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006571', 'Beni', 'Liam', '36006571@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant (`numEtudiant`, `nom`, `prenom`, `email`, `niveaux`) VALUES ('36006572', 'Peru', 'Paul', '36006572@parisnanterre.fr', 'M1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('1','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('2','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('3','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('4','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('5','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('6','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('7','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('8','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('9','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('10','1');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('11','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('12','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('13','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('14','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('15','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('16','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('17','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('18','3');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('19','3');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('20','3');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('21','3');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('22','3');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('23','3');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('24','3');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('25','3');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('26','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('27','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('28','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('29','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('30','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('31','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('32','2');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('33','6');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('34','6');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('35','6');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('36','6');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('37','6');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('38','6');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('39','6');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('40','6');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('11','4');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('12','4');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('13','4');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('14','4');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('15','4');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('16','4');
INSERT INTO listes_etudiant_filieres (`etudiant_id`, `filiere_id`) VALUES ('17','4');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('1', '2');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('1', '5');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('2', '2');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('3', '5');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('4', '5');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('5', '3');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('6', '3');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('7', '4');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('8', '4');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('9', '1');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('10', '1');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('11', '6');
INSERT INTO listes_cours_filieres(`cours_id`, `filiere_id`) VALUES ('12', '6');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('1', '2');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('1', '3');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('2', '9');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('2', '10');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('3', '11');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('3', '12');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('4', '5');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('1', '1');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('3', '4');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('1', '7');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('1', '8');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('4', '6');
INSERT INTO listes_professeur_cours(`professeur_id`, `cours_id`) VALUES ('3', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('1', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('2', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('3', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('4', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('5', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('6', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('7', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('8', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('9', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('10', '9');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('1', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('2', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('3', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('4', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('5', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('6', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('7', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('8', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('9', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('10', '10');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('24', '3');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('25', '3');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('26', '3');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('27', '3');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('28', '3');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('29', '3');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('24', '4');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('25', '4');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('26', '4');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('27', '4');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('28', '4');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('29', '4');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('11', '1');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('12', '1');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('13', '1');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('14', '1');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('15', '1');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('16', '1');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('17', '1');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('11', '2');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('12', '2');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('13', '2');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('14', '2');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('15', '2');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('16', '2');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('17', '2');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('36', '11');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('37', '11');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('38', '11');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('39', '11');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('40', '11');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('36', '12');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('37', '12');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('38', '12');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('39', '12');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('40', '12');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('18', '5');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('19', '5');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('20', '5');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('21', '5');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('22', '5');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('23', '5');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('18', '6');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('19', '6');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('20', '6');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('21', '6');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('22', '6');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('23', '6');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('30', '7');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('31', '7');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('32', '7');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('33', '7');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('34', '7');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('35', '7');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('30', '8');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('31', '8');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('32', '8');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('33', '8');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('34', '8');
INSERT INTO listes_etudiant_cours(`etudiant_id`, `cours_id`) VALUES ('35', '8');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2016-09-09', '2017-07-07', 'L1', 'Université Paris Nanterre', '5', '1');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2017-09-09', '2018-07-07', 'L2', 'Université Paris Nanterre', '5', '1');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2018-09-09', '2019-07-07', 'L3', 'Université Paris Nanterre', '1', '1');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M1', 'Université Paris Nanterre', '1', '1');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M2', 'Université Paris Nanterre', '1', '1');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2016-09-09', '2017-07-07', 'L1', 'Université Paris Nanterre', '5', '31');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2017-09-09', '2018-07-07', 'L2', 'Université Paris Nanterre', '5', '31');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2018-09-09', '2019-07-07', 'L3', 'Université Paris Nanterre', '1', '31');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M1', 'Université Paris Nanterre', '1', '31');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M2', 'Université Paris Nanterre', '1', '31');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2016-09-09', '2017-07-07', 'L1', 'Université Paris Nanterre', '5', '4');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2017-09-09', '2018-07-07', 'L2', 'Université Paris Nanterre', '5', '4');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2018-09-09', '2019-07-07', 'L3', 'Université Paris Nanterre', '1', '4');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M1', 'Université Paris Nanterre', '1', '4');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M2', 'Université Paris Nanterre', '1', '4');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2016-09-09', '2017-07-07', 'L1', 'Université Paris Nanterre', '5', '9');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2017-09-09', '2018-07-07', 'L2', 'Université Paris Nanterre', '5', '9');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2018-09-09', '2019-07-07', 'L3', 'Université Paris Nanterre', '1', '9');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M1', 'Université Paris Nanterre', '1', '9');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M2', 'Université Paris Nanterre', '1', '9');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2016-09-09', '2017-07-07', 'L1', 'Université Paris Nanterre', '5', '10');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2017-09-09', '2018-07-07', 'L2', 'Université Paris Nanterre', '5', '10');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2018-09-09', '2019-07-07', 'L3', 'Université Paris Nanterre', '1', '10');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M1', 'Université Paris Nanterre', '1', '10');
INSERT INTO listes_cursus (`debut`, `fin`, `niveaux`, `etablissement`, `filiere_id`, `etudiant_id`) VALUES ('2019-09-09', '2020-07-07', 'M2', 'Université Paris Nanterre', '1', '10');